# Basic stable formatting options only
# (Unstable options removed for CI compatibility)
hard_tabs = false
tab_spaces = 4
max_width = 100
use_small_heuristics = "Max"

# Consistency
newline_style = "Unix"
use_field_init_shorthand = true
