# Basic
hard_tabs = false
tab_spaces = 4
max_width = 100
use_small_heuristics = "Max"

# Imports
imports_granularity = "Crate"
reorder_imports = true

# Consistency
newline_style = "Unix"

# Misc
binop_separator = "Front"
chain_width = 80
match_arm_blocks = false
match_block_trailing_comma = true
reorder_impl_items = false
spaces_around_ranges = false
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true
