# cargo-deny configuration for wasm-chord
# Documentation: https://embarkstudios.github.io/cargo-deny/

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "wasm32-unknown-unknown" },
]
all-features = false
no-default-features = false

[output]
feature-depth = 1

# Advisory checks
[advisories]
ignore = [
    # Add specific advisories to ignore here if needed
    # Example: { id = "RUSTSEC-2020-0071", reason = "Waiting for upstream fix" }
]

# License checks
[licenses]
unused-allowed-license = "warn"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MPL-2.0",
    "Unicode-DFS-2016",
    "Zlib",
]
confidence-threshold = 0.8

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[licenses.private]
ignore = false

# Ban checks
[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

allow = []
deny = []

skip = []
skip-tree = []

# Source checks
[sources]
unknown-registry = "deny"
unknown-git = "warn"

allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = ["RustCrypto"]
