[package]
name = "vocab-check"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vocab-check"
path = "main.rs"

[dependencies]
wasm-chord-core = { path = "../../crates/wasm-chord-core" }
wasm-chord-runtime = { path = "../../crates/wasm-chord-runtime" }
