[package]
name = "debug-generation-timeout"
version.workspace = true
edition.workspace = true

[[bin]]
name = "debug-generation-timeout"
path = "main.rs"

[dependencies]
wasm-chord-core.workspace = true
wasm-chord-runtime.workspace = true

