[package]
name = "wasm-chord-tokenizer-debug"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tokenizer-debug"
path = "main.rs"

[dependencies]
wasm-chord-core = { path = "../../crates/wasm-chord-core" }
wasm-chord-runtime = { path = "../../crates/wasm-chord-runtime" }
