[package]
name = "wasm-chord-coherence-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "coherence-test"
path = "main.rs"

[dependencies]
wasm-chord-core = { path = "../../crates/wasm-chord-core" }
wasm-chord-runtime = { path = "../../crates/wasm-chord-runtime" }
serde_json = "1.0"
