[package]
name = "cache-test"
version.workspace = true
edition.workspace = true

[[bin]]
doc = false
name = "cache-test"
path = "main.rs"

[dependencies]
wasm-chord-core.workspace = true
wasm-chord-runtime.workspace = true
