[package]
name = "gpu-test"
version.workspace = true
edition.workspace = true

[[bin]]
doc = false
name = "gpu-test"
path = "main.rs"

[dependencies]
wasm-chord-core.workspace = true
wasm-chord-runtime.workspace = true

[features]
default = []
gpu = ["wasm-chord-runtime/gpu"]
