[package]
name = "wasm-10gb-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wasm-10gb-test"
path = "main.rs"
doc = false

[dependencies]
wasm-chord-runtime = { path = "../../crates/wasm-chord-runtime" }

[features]
memory64 = ["wasm-chord-runtime/memory64"]
